{
 "title": "UserService",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Ingress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{}[$__rate_interval]))",
     "legendFormat": "RPS"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, \n      sum by (le)\n         (rate(nginx_ingress_controller_request_duration_seconds_bucket[$__rate_interval]))\n) * 1000",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.95, \n      sum by (le)\n         (rate(nginx_ingress_controller_request_duration_seconds_bucket[$__rate_interval]))\n) * 1000",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.99, \n      sum by (le)\n         (rate(nginx_ingress_controller_request_duration_seconds_bucket[$__rate_interval]))\n) * 1000",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(1, \n      sum by (le)\n         (rate(nginx_ingress_controller_request_duration_seconds_bucket[$__rate_interval]))\n) * 1000",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "5xx Errors Rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_count{status=~\"5.+\"}[$__rate_interval]) or vector(0)) /\nsum(rate(nginx_ingress_controller_request_duration_seconds_count{}[$__rate_interval])) * 100"
    }
   ]
  },
  {
   "title": "5xx Errors",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 4 },
   "targets": [
    {
     "expr": "sum by (status) (increase(nginx_ingress_controller_request_duration_seconds_count{status=~\"5.+\"}[$__interval]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  { "title": "UserService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by (method, exported_endpoint) (rate(app_request_count{}[$__rate_interval]))",
     "legendFormat": "{{method}} {{exported_endpoint}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, \n      sum by (le, method, exported_endpoint) \n         (rate(app_request_latency_seconds_bucket[$__rate_interval]))\n) * 1000\n",
     "legendFormat": "0.5: {{method}} {{exported_endpoint}}"
    },
    {
     "expr": "histogram_quantile(0.95, \n      sum by (le, method, exported_endpoint) \n         (rate(app_request_latency_seconds_bucket[$__rate_interval]))\n) * 1000\n",
     "legendFormat": "0.95: {{method}} {{exported_endpoint}}"
    },
    {
     "expr": "histogram_quantile(0.99, \n      sum by (le, method, exported_endpoint) \n         (rate(app_request_latency_seconds_bucket[$__rate_interval]))\n) * 1000\n",
     "legendFormat": "0.99: {{method}} {{exported_endpoint}}"
    },
    {
     "expr": "histogram_quantile(1, \n      sum by (le, method, exported_endpoint) \n         (rate(app_request_latency_seconds_bucket[$__rate_interval]))\n) * 1000\n",
     "legendFormat": "max: {{method}} {{exported_endpoint}}"
    }
   ]
  },
  {
   "title": "5xx Errors Rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(app_request_count{http_status=~\"5.+\"}[$__rate_interval]) or vector(0)) /\nsum(rate(app_request_count{}[$__rate_interval])) * 100"
    }
   ]
  },
  {
   "title": "5xx Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 13 },
   "targets": [
    {
     "expr": "sum by (method, exported_endpoint, http_status) (increase(app_request_count{http_status=~\"5.+\"}[$__interval]))",
     "legendFormat": "{{http_status}}: {{method}} {{exported_endpoint}}"
    }
   ]
  }
 ]
}