replicaCount: 2

image:
  repository: klwxsrx/arch-course-labs-02-user-service

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: arch.homework
      paths:
        - path: /
          pathType: Prefix

metrics:
  serviceMonitor:
    enabled: true

mysql:
  image:
    repository: bitnami/mysql
    tag: "8.0"
  auth:
    database: user
    username: user
    password: test1234
  primary:
    service:
      port: 3306