@startuml

activate Order

Order -> Payment: AuthorizeOrderPayment
activate Payment

Order <-- Payment: OK
deactivate Payment

Order -> Stock: ReserveOrderItems
activate Stock

Order <-- Stock: OK
deactivate Stock

Order -> Delivery: ScheduleDelivery
activate Delivery

Order <-- Delivery: OK
deactivate Delivery

Order -> Payment: CompletePaymentTransaction
activate Payment

alt #lightgreen Успешное подтверждение платежа

Order <-- Payment: OK

else #lightpink Откат операций

Order <-- Payment: ERROR
deactivate Payment

Order -> Delivery: RemoveDeliverySchedule
activate Delivery

Order <-- Delivery: OK
deactivate Delivery

Order -> Stock: RemoveOrderItemsReservation
activate Stock

Order <-- Stock: OK
deactivate Stock

Order -> Payment: CancelOrderPayment\n(можно не вызывать в случае отклонения платежа)
activate Payment

Order <-- Payment: OK
deactivate Payment
deactivate Order

end

@enduml