apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "user-service.fullname" . }}
  labels: {{ include "user-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{ include "user-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{ include "user-service.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ .Chart.AppVersion }}
          env:
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: user-service-config
                  key: mysql-host
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: user-service-config
                  key: mysql-port
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: user-service-db-access
                  key: mysql-database
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: user-service-db-access
                  key: mysql-user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-service-db-access
                  key: mysql-password
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080