apiVersion: v1
kind: ConfigMap
metadata:
  name: userservice-config
data:
  database-host: userservice-db-mysql # TODO: helm var
  database-port: "3306" # TODO: helm var
---
apiVersion: v1
kind: Secret
metadata:
  name: userservice-db-access
type: Opaque
stringData:
  mysql-database: user
  mysql-user: user
  mysql-password: test1234

# TODO: helm install --set "image.tag=8.0" --set "auth.database=user" --set "auth.username=user" --set "auth.password=test1234" userservice-db bitnami/mysql