apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: auth
  namespace: user
spec:
  forwardAuth:
    address: http://auth.user.svc.cluster.local:8080/auth
    authResponseHeaders:
      - X-Auth-User-ID
      - X-Auth-User-Login
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: user
  namespace: user
spec:
  routes:
    - kind: Rule
      match: PathPrefix(`/profile`)
      priority: 1
      services:
        - name: userprofile
          namespace: user
          port: 8080
      middlewares:
        - name: auth
          namespace: user
    - kind: Rule
      match: PathPrefix(`/auth`)
      priority: 2
      services:
        - name: auth
          namespace: user
          port: 8080