apiVersion: v1
kind: ConfigMap
metadata:
  name: order-config
  namespace: arch-course
data:
  mysql-host: arch-course-db-mysql
  mysql-port: "3306"
---
apiVersion: v1
kind: Secret
metadata:
  name: order-db-access
  namespace: arch-course
type: Opaque
stringData:
  mysql-database: archcourse
  mysql-user: user
  mysql-password: test1234
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-config
  namespace: arch-course
data:
  mysql-host: arch-course-db-mysql
  mysql-port: "3306"
---
apiVersion: v1
kind: Secret
metadata:
  name: payment-db-access
  namespace: arch-course
type: Opaque
stringData:
  mysql-database: archcourse
  mysql-user: user
  mysql-password: test1234
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: warehouse-config
  namespace: arch-course
data:
  mysql-host: arch-course-db-mysql
  mysql-port: "3306"
---
apiVersion: v1
kind: Secret
metadata:
  name: warehouse-db-access
  namespace: arch-course
type: Opaque
stringData:
  mysql-database: archcourse
  mysql-user: user
  mysql-password: test1234
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: delivery-config
  namespace: arch-course
data:
  mysql-host: arch-course-db-mysql
  mysql-port: "3306"
---
apiVersion: v1
kind: Secret
metadata:
  name: delivery-db-access
  namespace: arch-course
type: Opaque
stringData:
  mysql-database: archcourse
  mysql-user: user
  mysql-password: test1234